### Activity 5.1 {-}

Indicate what type of t-test could be used to analyse the data from the following studies and provide reasons:

a) A total of 60 university students are randomly assigned to undergo either behaviour therapy or Gestalt therapy. After twenty therapeutic sessions, each student earns a score on a mental health questionnaire.
b) A researcher wishes to determine whether attendance at a day care centre increases the scores of three year old twins on a motor skills test. Random assignment is used to decide which member from each of 30 pairs of twins attends the day care centre and which member stays at home.
c) A child psychologist assigns aggression scores to each of 10 children during two 60 minute observation periods separated by an intervening exposure to a series of violent TV cartoons.
d) A marketing researcher measures 100 doctors’ reports of the number of their patients asking them about a particular drug during the month before and the month after a major advertising campaign.

### Activity 5.2 {-}
A study was conducted to compare haemoglobin levels in the blood of children with and without cystic fibrosis. It is known that haemoglobin levels are normally distributed in children. The study results are given below:

```{r act-5-2, echo=FALSE}
library(huxtable)

df <- tibble::tribble(
  ~Statistic, ~`Children without CF`, ~`Children with CF`,
  "n",                "12",              "15",
  "Mean",              "19.9",            "13.9",
  "SD (SE)",        "5.9 (1.70)",      "6.2 (1.60)"
  )
huxtable::huxtable(df) |> 
  theme_article() |> 
  set_width(0.8) |> 
  set_caption("Summary of haemoglobin (g/dL)")
```

a) State the appropriate null hypothesis and alternate hypothesis
b) Use Stata to conduct an appropriate statistical test to evaluate the null hypothesis. Are the assumptions for the test met for this analysis to be valid?

### Activity 5.3 {-}
A randomised controlled trial (RCT) was carried out to investigate the effect of a new tablet supplement in increasing the hematocrit (%) value in anaemic participants. In the study, hematocrit was measured as the proportion of blood that is made up of red blood cells. Hematocrit levels are often lower in anaemic people who do not have sufficient healthy red blood cells. In the RCT, 33 people in the intervention group received the new supplement and 31 people in the control group received standard care (i.e. the usual supplement was given). After 4 weeks, hematocrit values were measured as shown in the Stata file `ActivityS5.3.dta`. In the community, hematocrit levels are normally distributed.

a) State the research question and frame it as a null hypothesis. 
b) Use Stata to conduct an appropriate statistical test to answer the research question. Before using the test, check the data to see if the assumptions required for the test are met. Obtain a box plot to obtain an estimate of the centre and spread of the data for each group.
c) Run your statistical test. 
d) Construct a table to show how you would report your results and write a conclusion.

### Activity 5.4 {-}
A total of 41 babies aged 6 months to 2 years with haemangioma (birth mark) were enrolled in a study to test the effect of a new topical medication in reducing the volume of their haemangioma. Parents were asked to apply the medication twice daily. The volume (in mm3) of the haemangioma was measured at enrolment and again after 12 weeks of using the medication.

a) What is the research question in this study? State the null and alternative hypotheses.
b) Use the data in the Stata file `ActivityS5.4.dta` to answer the research question. Which statistical test is appropriate to answer the research question and why? Conduct the test in Stata and write your conclusion.
c) What are the limitations of this study?
