# Course introduction {-}

Welcome to PHCM9795 Foundations of Biostatistics.

This introductory course in biostatistics aims to provide students with core biostatistical skills to analyse and present quantitative data from different study types. These are essential skills required in your degree and throughout your career.

We hope you enjoy the course and will value your feedback and comment throughout the course.

## Course information {-}

Biostatistics is a foundational discipline needed for the analysis and interpretation of quantitative information and its application to population health policy and practice. 

This course is central to becoming a population health practitioner as the concepts and techniques developed in the course are fundamental to your studies and practice in population health. In this course you will develop an understanding of, and skills in, the core concepts of biostatistics that are necessary for analysis and interpretation of population health data and health literature. 

In designing this course, we provide a learning sequence that will allow you to obtain the required graduate capabilities identified for your program. This course is taught with an emphasis on formulating a hypothesis and quantifying the evidence in relation to a specific research question. You will have the opportunity to analyse data from different study types commonly seen in population health research.

The course will allow those of you who have covered some of this material in your undergraduate and other professional education to consolidate your knowledge and skills.  Students exposed to biostatistics for the first time may find the course challenging at times. Based on student feedback, the key to success in this course is to devote time to it every week. We recommend that you spend an average of 10-15 hours per week on the course, including the time spent reading the course notes and readings, listening to lectures, and working through learning activities and completing your assessments. Please use the resources provided to assist you, including online support.

## Units of credit {-}
This course is a core course of the Master of Public Health, Master of Global Health and Master of Infectious Diseases Intelligence programs and associated dual degrees, comprising 6 units of credit towards the total required for completion of the study program. A value of 6 UOC requires a minimum of 150 hours work for the average student across the term.

## Course aim {-}
This course aims to provide students with the core biostatistical skills to apply appropriate statistical techniques to analyse and present population health data.

## Learning outcomes {-}
On successful completion of this course, you will be able to:

1. Summarise and visualise data using statistical software.
2. Demonstrate an understanding of statistical inference by interpreting p-values and confidence intervals.
3. Apply appropriate statistical tests for different types of variables given a research question, and interpret computer output of these tests appropriately.
4. Determine the appropriate sample size when planning a research study.
5. Present and interpret statistical findings appropriate for a population health audience.


### Changelog {-}

**2023-07-17**

[Changed]

- Section 7.9: Corrected screenshots to test difference in paired proportions in Stata.

**2023-07-13**

[Changed]

- Section 7.13: tidied up the R function used to calculate the 95% confidence interval for the difference in paired proportions.

**2023-07-12**

[Changed]

- Worked Example 6.2: removed "This z-statistic does not meet or exceed the critical value of 1.96 for a two tailed test" and re-framed this in terms of interpreting the P-value as calculated from software.
- Worked Example 7.1: corrected column headings for Nausea and No nausea

**2023-07-01**

[Changed]

- Section 4.2: Fixed typo: "The particular test statistic differs depending on the type of data being ~~analyses~~ analysed"
- Section 4.4: Fixed typo: "This is the situation described in scenario (c) of ~~Figure~~ Figure 4.1."
- Activity 5.2: Added "or R" to the instruction "Use Stata to conduct an appropriate statistical test"
- Activity 5.3: Added "or R" to the instruction "Use Stata to conduct an appropriate statistical test"
- Section 6.3: Fixed formula for testing one sample proportion to: "$z = \frac{(p_{sample} - p_{population})}{\text{SE}(p_{population})}$"
- Activity 7.2: Added "or R" to the instruction "Using Stata, carry out the appropriate significance test"

**2023-07-01**

[Changed]

- Renamed "Readings" to "Optional readings"
- Module 4, Section 4.8: Corrected the sentence that describes Figure 4.4. "the shaded region for a one-tailed test would be ~~doubled~~ retained on one side of the distribution and eliminated from the other side of the distribution".
- Module 9: Added titles to Tables 9.3 and 9.4.
- Module 9, Section 9.4: Corrected the level of evidence: "providing ~~strong~~ evidence of a difference in the median length of stay between the groups."
- Module 9, Section 9.5.1. Corrected the text under Table 9.4: "The data shows ... 10 people who have a ~~negative~~ positive difference."


**2023-06-13**

[Changed]

- Module 3. Clarified Worked Example 3.1, and moved the example from Section 3.5.1 to Section 3.5.2.
- Section 3.6: Added Stata output for calculating a 95% confidence interval from individual data.

**2023-06-01**

[Changed]

- Section 1.14.3: RStudio preferences are now located at **Edit \> Settings** on MacOS, and **Tools \> Global Options** on Windows
- Section 1.14.7.2: Correct layout for commands to install packages (commands must be entered on separate lines)
- Section 1.15.2: Correct the name of the pbc data set to mod_01_pdc.rds
- Activity 2.3(b): Change the request to plot data on a Normal curve, not a standardised Normal curve
- Activity 5.3 and 5.4: added underscores to filenames

