<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>PHCM9795: Foundations of Biostatistics - 3&nbsp; Precision, standard errors and confidence intervals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-hypothesis-testing.html" rel="next">
<link href="./02-probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: #ffdc00;
      }
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-precision.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Precision, standard errors and confidence intervals</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Precision, standard errors and confidence intervals</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PHCM9795: Foundations of Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to statistics and presenting data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability and probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-precision.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Precision, standard errors and confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comparing-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-testing-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-correlation-and-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-non-parametrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sample size estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98.1-appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings">Readings</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">3.1</span> Introduction</a></li>
  <li><a href="#sampling-methods" id="toc-sampling-methods" class="nav-link" data-scroll-target="#sampling-methods"><span class="header-section-number">3.2</span> Sampling methods</a></li>
  <li><a href="#standard-error-and-precision" id="toc-standard-error-and-precision" class="nav-link" data-scroll-target="#standard-error-and-precision"><span class="header-section-number">3.3</span> Standard error and precision</a>
  <ul class="collapse">
  <li><a href="#the-standard-error-of-the-mean" id="toc-the-standard-error-of-the-mean" class="nav-link" data-scroll-target="#the-standard-error-of-the-mean"><span class="header-section-number">3.3.1</span> The standard error of the mean</a></li>
  </ul></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem"><span class="header-section-number">3.4</span> Central limit theorem</a>
  <ul class="collapse">
  <li><a href="#when-the-population-distribution-is-unknown" id="toc-when-the-population-distribution-is-unknown" class="nav-link" data-scroll-target="#when-the-population-distribution-is-unknown"><span class="header-section-number">3.4.1</span> When the population distribution is unknown:</a></li>
  <li><a href="#when-the-population-is-assumed-to-be-normal" id="toc-when-the-population-is-assumed-to-be-normal" class="nav-link" data-scroll-target="#when-the-population-is-assumed-to-be-normal"><span class="header-section-number">3.4.2</span> When the population is assumed to be normal:</a></li>
  </ul></li>
  <li><a href="#confidence-interval-of-the-mean" id="toc-confidence-interval-of-the-mean" class="nav-link" data-scroll-target="#confidence-interval-of-the-mean"><span class="header-section-number">3.5</span> 95% confidence interval of the mean</a>
  <ul class="collapse">
  <li><a href="#worked-example-3.1-95-ci-of-a-mean" id="toc-worked-example-3.1-95-ci-of-a-mean" class="nav-link" data-scroll-target="#worked-example-3.1-95-ci-of-a-mean"><span class="header-section-number">3.5.1</span> Worked Example 3.1: 95% CI of a mean</a></li>
  <li><a href="#the-t-distribution-and-when-should-i-use-it" id="toc-the-t-distribution-and-when-should-i-use-it" class="nav-link" data-scroll-target="#the-t-distribution-and-when-should-i-use-it"><span class="header-section-number">3.5.2</span> The t-distribution and when should I use it?</a></li>
  <li><a href="#worked-example-3.2" id="toc-worked-example-3.2" class="nav-link" data-scroll-target="#worked-example-3.2"><span class="header-section-number">3.5.3</span> Worked Example 3.2</a></li>
  </ul></li>
  <li><a href="#stata-notes" id="toc-stata-notes" class="nav-link" data-scroll-target="#stata-notes">Stata notes</a>
  <ul class="collapse">
  <li><a href="#sec-cimean-stata-ind" id="toc-sec-cimean-stata-ind" class="nav-link" data-scroll-target="#sec-cimean-stata-ind"><span class="header-section-number">3.6</span> Calculating a 95% confidence interval of a mean: Individual data</a></li>
  <li><a href="#sec-cimean-stata-summ" id="toc-sec-cimean-stata-summ" class="nav-link" data-scroll-target="#sec-cimean-stata-summ"><span class="header-section-number">3.7</span> Calculating a 95% confidence interval of a mean: Summarised data</a></li>
  </ul></li>
  <li><a href="#r-notes" id="toc-r-notes" class="nav-link" data-scroll-target="#r-notes">R notes</a>
  <ul class="collapse">
  <li><a href="#sec-cimean-r-ind" id="toc-sec-cimean-r-ind" class="nav-link" data-scroll-target="#sec-cimean-r-ind"><span class="header-section-number">3.8</span> Calculating a 95% confidence interval of a mean: individual data</a></li>
  <li><a href="#sec-cimean-r-summ" id="toc-sec-cimean-r-summ" class="nav-link" data-scroll-target="#sec-cimean-r-summ"><span class="header-section-number">3.9</span> Calculating a 95% confidence interval of a mean: summarised data</a></li>
  </ul></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a>
  <ul class="collapse">
  <li><a href="#activity-3.1" id="toc-activity-3.1" class="nav-link" data-scroll-target="#activity-3.1">Activity 3.1</a></li>
  <li><a href="#activity-3.2" id="toc-activity-3.2" class="nav-link" data-scroll-target="#activity-3.2">Activity 3.2</a></li>
  <li><a href="#activity-3.3" id="toc-activity-3.3" class="nav-link" data-scroll-target="#activity-3.3">Activity 3.3</a></li>
  <li><a href="#activity-3.4" id="toc-activity-3.4" class="nav-link" data-scroll-target="#activity-3.4">Activity 3.4</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>By the end of this module you will be able to:</p>
<ul>
<li>Explain the purpose of sampling, different sampling methods and their implications for data analysis;</li>
<li>Distinguish between standard deviation of a sample and standard error of a mean;</li>
<li>Recognise the importance of the central limit theorem;</li>
<li>Calculate the standard error of a mean;</li>
<li>Calculate and interpret confidence intervals for a mean;</li>
<li>Be familiar with the t-distribution and when to use it.</li>
</ul>
</section>
<section id="readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="readings">Readings</h2>
<p><span class="citation" data-cites="kirkwood_sterne01">Kirkwood and Sterne (<a href="references.html#ref-kirkwood_sterne01" role="doc-biblioref">2001</a>)</span>; Chapters 4 and 6. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728">[UNSW Library Link]</a></p>
<p><span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>; Sections 3.3 and 3.4, 8.1 to 8.3. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730">[UNSW Library Link]</a></p>
</section>
<section id="introduction" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">3.1</span> Introduction</h2>
<p>To describe the characteristics of a population we can gather data about the entire population (as is undertaken in a national census) or we can gather data from a sample of the population. When undertaking a research study, taking a sample from a population is far more cost-effective and less time consuming than collecting information from the entire population. When a sample of a population is selected, summary statistics that describe the sample are used to make inferences about the total population from which the sample was drawn. These are referred to as inferential statistics.</p>
<p>However, for the inferences about the population to be valid, a random sample of the population must be obtained. The goal of using random sampling methods is to obtain a sample that is representative of the target population. In other words, apart from random error, the information derived from the sample is expected to be much the same as the information collected from a complete population census as long as the sample is large enough.</p>
</section>
<section id="sampling-methods" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sampling-methods"><span class="header-section-number">3.2</span> Sampling methods</h2>
<p>Methods have been designed to select participants from a population such that each person in the target population has an equal probability of being chosen. Methods that use this approach are called random sampling methods. Examples include simple random sampling and stratified random sampling.</p>
<p>In simple random sampling, every person in the population from which the sample is drawn has the same random chance of being selected into the sample. To implement this method, every person in the population is allocated an ID number and then a random sample of the ID numbers is selected. Software packages can be used to generate a list of random numbers to select the random sample.</p>
<p>In stratified sampling, the population is divided into distinct non-overlapping subgroups (strata) according to an important characteristic (e.g.&nbsp;age or sex) and then a random sample is selected from each of the strata. This method is used to ensure that sufficient numbers of people are sampled from each stratum and therefore each subgroup of interest is adequately represented in the sample.</p>
<p>The purpose of using random sampling is to minimise selection bias to ensure that the sample enrolled in a study is representative of the population being studied. This is important because the summary statistics that are obtained can then be regarded as valid in that they can be applied (generalised) back to the population.</p>
<p>A non-representative sample might occur when random sampling is used, simply by chance. However, non-random sampling methods, such as using a study population that does not represent the whole population, will often result in a non-representative sample being selected so that the summary statistics from the sample cannot be generalised back to the population from which the participants were drawn. The effects of non-random error are much more serious than the effects of random error. Concepts such as non-random error (i.e.&nbsp;systematic bias), selection bias, validity and generalisability are discussed in more detail in PHCM9796: Foundations of Epidemiology.</p>
</section>
<section id="standard-error-and-precision" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="standard-error-and-precision"><span class="header-section-number">3.3</span> Standard error and precision</h2>
<p>Module 1 introduced the mean, variance and standard deviation as measures of central tendency and spread for continuous measurements from a sample or a population. As described in Module 1, we rarely have data on the entire population but we can infer information about the population (e.g.&nbsp;the mean weight of people in the population) based on a sample. However, a sample taken from a population is usually a small proportion of the total population. If the sample is very small, we would not expect our estimate of the population mean value to be precise. If the sample is very large, we would expect a more precise estimate of the population mean, i.e.&nbsp;the estimated mean value would be much closer to the true mean value in the population.</p>
<section id="the-standard-error-of-the-mean" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="the-standard-error-of-the-mean"><span class="header-section-number">3.3.1</span> The standard error of the mean</h3>
<p>A point estimate is a single best guess of the true value in the population. Instead of trying to guess the true value, it may be preferable to give a range of values in which we think the true value lies. For example, suppose we want to estimate the average weight of a population, and found a sample mean of 65 kg. Rather than saying we believe the true mean to be 65 kg, we could say we believe it is somewhere between, say, 58 kg and 72 kg.</p>
<p>Often in papers, one will see something like “the mean is 70.24 <span class="math inline">\(\pm\)</span> 1.78 kg”. The value 1.78 is the <em>standard error of the mean</em> (sometimes shortened to S.E.M. or S.E.). The standard error of the mean measures the extent to which we expect the means from different samples to vary because of chance error in the sampling process. The standard error is a measure of precision of the point estimate. This statistic is directly proportional to the standard deviation of the variable, and inversely proportional to the size of the sample. The standard error of the mean for a continuously distributed measurement for which the SD is an accurate measure of spread is computed as follows:</p>
<p><span class="math display">\[ \text{SE}(\bar{x}) = \frac{\text{SD}}{\sqrt{n}} \]</span> For our sample of weight data from 30 patients in Module 1:</p>
<p><span class="math display">\[ \text{SE}(\bar{x}) = \frac{\text{5.04}}{\sqrt{30}} = 0.92 \]</span> Because the calculation uses the sample size (n) (i.e.&nbsp;the number of study participants) in the denominator, the SE will become smaller when the sample size becomes larger. A smaller SE indicates that the estimated mean value is more precise.</p>
<p>The standard error is an important statistic that is related to sampling variation. When a random sample of a population is selected, it is likely to differ in some characteristic compared with another random sample selected from the same population. Also, when a sample of a population is taken, the true population mean is an unknown value.</p>
<p>Just as the standard deviation measures the spread of the data around the population mean, the standard error of the mean measures the spread of the sample means. Note that we do not have different samples, only one. It is a theoretical concept which enables us to conduct various other statistical analyses.</p>
</section>
</section>
<section id="central-limit-theorem" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="central-limit-theorem"><span class="header-section-number">3.4</span> Central limit theorem</h2>
<p>Even though we now have an estimate of the mean and its standard error, we might like to know what the mean from a different random sample of the same size might be. To do this, we need to know how sample means are distributed. In determining the form of the probability distribution of the sample mean (<span class="math inline">\(\bar{x}\)</span>), we consider two cases:</p>
<section id="when-the-population-distribution-is-unknown" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="when-the-population-distribution-is-unknown"><span class="header-section-number">3.4.1</span> When the population distribution is unknown:</h3>
<p>The central limit theorem for this situation states:</p>
<blockquote class="blockquote">
<p>In selecting random samples of size <span class="math inline">\(n\)</span> from a population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>, the sampling distribution of the sample mean <span class="math inline">\(\bar{x}\)</span> approaches a normal distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\tfrac{\sigma}{\sqrt{n}}\)</span> as the sample size becomes large.</p>
</blockquote>
<p>The sample size n = 30 and above is a rule of thumb for the central limit theorem to be used. However, larger sample sizes may be needed if the distribution is highly skewed.</p>
</section>
<section id="when-the-population-is-assumed-to-be-normal" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="when-the-population-is-assumed-to-be-normal"><span class="header-section-number">3.4.2</span> When the population is assumed to be normal:</h3>
<p>In this case the sampling distribution of <span class="math inline">\(\bar{x}\)</span> is normal for any sample size.</p>
</section>
</section>
<section id="confidence-interval-of-the-mean" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="confidence-interval-of-the-mean"><span class="header-section-number">3.5</span> 95% confidence interval of the mean</h2>
<p>In Module 2, we showed that the characteristics of a Standard Normal Distribution are that 95% of the data lie within 1.96 standard deviations from the mean (<a href="02-probability.html#fig-2-2">Figure&nbsp;<span>2.2</span></a>). Because the central limit theorem states that the sampling distribution of the mean is approximately Normal in large enough samples, we expect that 95% of the mean values would fall within 1.96 × SE units above and below the measured mean population value.</p>
<p>For example, if we repeated the study on weight 100 times using 100 different random samples from the population and calculated the mean weight for each of the 100 samples, approximately 95% of the values for the mean weight calculated for each of the 100 samples would fall within 1.96 × SE of the population mean weight.</p>
<p>This interpretation of the SE is translated into the concept of precision as a 95% confidence interval (CI). A 95% CI is a range of values within which we have 95% confidence that the true population mean lies. If an experiment was conducted a very large number of times, and a 95%CI was calculated for each experiment, 95% of the confidence intervals would contain the true population mean.</p>
<p>The calculation of the 95% CI for a mean is as follows:</p>
<p><span class="math display">\[  \bar{x} \pm 1.96 \times \text{SE}( \bar{x} ) \]</span> This is the generic formula for calculating 95% CI for any summary statistic. In general, the mean value can be replaced by the point estimate of a rate or a proportion and the same formula applies for computing 95% CIs, i.e.</p>
<p><span class="math display">\[ 95\% \text{ CI} = \text{point estimate} \pm 1.96 \times \text{SE}(\text{point estimate)} \]</span></p>
<p>The main difference in the methods used to calculate the 95% CI for different point estimates is the way the SE is calculated. The methods for calculating 95% CI around proportions and other ratio measures will be discussed in Module 6.</p>
<p>The use of 1.96 as a general critical value to compute the 95% CI is determined by sampling theory. For the confidence interval of the mean, the critical value (1.96) is based on normal distribution (true when the population SD is known). However, in practice, Stata and other statistical packages will provide slightly different confidence intervals because they use a critical value obtained from the t-distribution. The t-distribution approaches a normal distribution when the sample size approaches infinity, and is close to a normal distribution when the sample size is ≥30.The critical values obtained from the t-distribution are always larger than the corresponding critical value from the normal distribution. The difference gets smaller as the sample size becomes larger. For example, when the sample size n=10, the critical value from the t-distribution is 2.26 (rather than 1.96); when n= 30, the value is 2.05; when n=100, the value is 1.98; and when n=1000, the critical value is 1.96.</p>
<p>The critical value multiplied by SE (for normal distribution, 1.96 × SE) is called the maximum likely error for 95% confidence.</p>
<section id="worked-example-3.1-95-ci-of-a-mean" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="worked-example-3.1-95-ci-of-a-mean"><span class="header-section-number">3.5.1</span> Worked Example 3.1: 95% CI of a mean</h3>
<p>For our sample of weights data with standard error of 0.92:</p>
<p><span class="math display">\[
\begin{aligned}
\ 95\% \text{ CI}(\bar{x}) &amp;=  \bar{x} \pm 1.96 \times \text{SE}(\bar{x}) \\
&amp;= 70.0 \pm 1.96 \times 0.92 \\
&amp;= 68.2 \text{ to } 71.8 \text{kg}
\end{aligned}
\]</span> We interpret this confidence interval as: we are 95% confident that the true mean of the population from which our sample was drawn lies between 68.2 kg and 71.8 kg.</p>
<p>This calculation takes into account both the sample mean of 70.0 kg and the sampling error that has arisen by chance due to the sample size of 30 people.</p>
<p>For a 95% CI to be reported around a mean value, the data values need to be approximately normally distributed, as discussed in Module 2.</p>
</section>
<section id="the-t-distribution-and-when-should-i-use-it" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="the-t-distribution-and-when-should-i-use-it"><span class="header-section-number">3.5.2</span> The t-distribution and when should I use it?</h3>
<p>The population standard deviation (<span class="math inline">\(\sigma\)</span>) is required for calculation of the standard error. Usually, <span class="math inline">\(\sigma\)</span> is not known and the sample standard deviation (<span class="math inline">\(s\)</span>) is used to estimate it. It is known, however, that the sample standard deviation of a normally distributed variable underestimates the true value of <span class="math inline">\(\sigma\)</span>, particularly when the sample size is small.</p>
<p>Someone by the pseudonym of Student came up with the Student’s t distribution with (<span class="math inline">\(n-1\)</span>) degrees of freedom to account for this underestimation. It looks very much like the standardised normal distribution, only that it has fatter tails (<a href="#fig-mod03-z-t-dist">Figure&nbsp;<span>3.1</span></a>). As the degrees of freedom increase (i.e.&nbsp;as <span class="math inline">\(n\)</span> increases), the t-distribution gradually approaches the standard normal distribution. With a sufficiently large sample size, the Student’s t-distribution closely approximates the standardised normal distribution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod03-z-t-dist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/mod03/mod03-z-t-dist.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.1: The normal (Z) and the student’s t-distribution with 2, 5 and 30 degrees of freedom</figcaption>
</figure>
</div>
</div>
</div>
<p>If a variable <span class="math inline">\(X\)</span> is normally distributed and the population standard deviation <span class="math inline">\(\sigma\)</span> is known, using the normal distribution is appropriate. However, if <span class="math inline">\(\sigma\)</span> is not known then one should use the student t-distribution with (<span class="math inline">\(n – 1\)</span>) degrees of freedom.</p>
</section>
<section id="worked-example-3.2" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="worked-example-3.2"><span class="header-section-number">3.5.3</span> Worked Example 3.2</h3>
<p>The publication of a study using a sample of 242 participants reported a sample mean systolic blood pressure of 128.4 mmHg and a sample standard deviation of 19.56 mmhg. Find the 95% confidence interval for the mean systolic blood pressure.</p>
<p>In Stata we use the <code>cii means</code> command to compute the 95% confidence interval given the sample mean, sample standard deviation and the sample size (i.e.&nbsp;without using individual data from a dataset) (<a href="#sec-cimean-stata-summ"><span>Section&nbsp;3.7</span></a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>. cii means <span class="dv">242</span> <span class="fl">128.4</span> <span class="fl">19.56</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    Variable <span class="sc">|</span>        Obs        Mean    Std. Err.       [<span class="dv">95</span>% Conf. Interval]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="sc">-------------+---------------------------------------------------------------</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>             <span class="er">|</span>        <span class="dv">242</span>       <span class="fl">128.4</span>    <span class="fl">1.257364</span>        <span class="fl">125.9232</span>    <span class="fl">130.8768</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In R we use the <code>ci_mean</code> function provided in <a href="#sec-cimean-r-summ"><span>Section&nbsp;3.9</span></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_mean</span>(<span class="at">n=</span><span class="dv">242</span>, <span class="at">mean=</span><span class="fl">128.4</span>, <span class="at">sd=</span><span class="fl">19.56</span>, <span class="at">width=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI: 125.923 to 130.877"</code></pre>
</div>
</div>
<p>Both commands use the t-distribution, and the output can be interpreted as: we are 95% confident that the true mean systolic blood pressure of the population from which the sample was drawn lies between 125.9 kg and 130.9 mmHg.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="stata-notes" class="level1 unnumbered">
<h1 class="unnumbered">Stata notes</h1>
<section id="sec-cimean-stata-ind" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-cimean-stata-ind"><span class="header-section-number">3.6</span> Calculating a 95% confidence interval of a mean: Individual data</h2>
<p>To demonstrate the computation of the 95% confidence interval of a mean we have used data from <code>mod02_weight_30.dta</code>. To calculate the 95% confidence interval, go to <strong>Statistics &gt; Summaries, tables, and tests &gt; Summary and descriptive statistics &gt; Confidence intervals</strong>. In the <strong>ci</strong> dialog box, select <code>weight</code> as the <strong>Variable</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod3-ci" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/mod03/stata/mod3-ci.png" class="img-fluid figure-img" style="width:66.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.2: Calculating a confidence interval from individual data</figcaption>
</figure>
</div>
</div>
</div>
<p>Click <strong>OK</strong> or <strong>Submit</strong> to obtain Output 3.1.</p>
<p>[Command: <code>ci means weight</code>]</p>
</section>
<section id="sec-cimean-stata-summ" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-cimean-stata-summ"><span class="header-section-number">3.7</span> Calculating a 95% confidence interval of a mean: Summarised data</h2>
<p>For Worked Example 3.2 where we are given the sample mean, sample standard deviation and sample size, we use the <code>cii means</code> command. To calculate the 95% CI, go to <strong>Statistics &gt; Summaries, tables, and tests &gt; Summary and descriptive statistics &gt; Normal mean CI calculator</strong>. In the <strong>cii</strong> dialog box, check that the <strong>Normal mean</strong> button is selected, and enter <code>242</code> as the <strong>Sample size</strong>, <code>128.4</code> as the <strong>Sample mean</strong>, <code>19.56</code> as the <strong>Sample standard deviation</strong> and check that <code>95</code> in entered as the <strong>Confidence level</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod3-cii" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/mod03/stata/mod3-cii.png" class="img-fluid figure-img" style="width:66.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.3: Calculating a confidence interval from summarised data</figcaption>
</figure>
</div>
</div>
</div>
<p>Click <strong>OK</strong> or <strong>Submit</strong> to obtain the following output:</p>
<section id="stata-output-3.2-95ci-for-a-given-sample-mean-sample-standard-deviation-and-sample-size" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="stata-output-3.2-95ci-for-a-given-sample-mean-sample-standard-deviation-and-sample-size">Stata Output 3.2: 95%CI for a given sample mean, sample standard deviation and sample size</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>. cii means <span class="dv">242</span> <span class="fl">128.4</span> <span class="fl">19.56</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    Variable <span class="sc">|</span>        Obs        Mean    Std. Err.       [<span class="dv">95</span>% Conf. Interval]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="sc">-------------+---------------------------------------------------------------</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>             <span class="er">|</span>        <span class="dv">242</span>       <span class="fl">128.4</span>    <span class="fl">1.257364</span>        <span class="fl">125.9232</span>    <span class="fl">130.8768</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="r-notes" class="level1 unnumbered">
<h1 class="unnumbered">R notes</h1>
<section id="sec-cimean-r-ind" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="sec-cimean-r-ind"><span class="header-section-number">3.8</span> Calculating a 95% confidence interval of a mean: individual data</h2>
<p>To demonstrate the computation of the 95% confidence interval of a mean we have used data from <code>mod02_weight_30.rds</code> which contains the weights of 30 students:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>students <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/examples/mod02_weight_30.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can examine the data set using the <code>summary</code> command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(students)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     weight         gender  
 Min.   :60.00   Male  :16  
 1st Qu.:67.50   Female:14  
 Median :70.00              
 Mean   :70.00              
 3rd Qu.:74.38              
 Max.   :80.00              </code></pre>
</div>
</div>
<p>The mean and its 95% confidence interval can be obtained many ways in R. We will use the <code>t.test()</code> function installed in R to calculate the confidence interval:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(students<span class="sc">$</span>weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  students$weight
t = 76.029, df = 29, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 68.11694 71.88306
sample estimates:
mean of x 
       70 </code></pre>
</div>
</div>
<p>The output of the <code>t.test()</code> function gives us the sample mean (70.0 kg) as well as the 95% confidence interval around the mean: 68.1 to 71.9 kg.</p>
<p>Note: the <code>descriptives()</code> function within the <code>jmv</code> package also calculates a 95% confidence interval around the mean. <strong>It is recommended not to use this function</strong> as it currently (as of June 2022) uses a <em>z</em> value to calculate the confidence interval, rather than a <em>t</em> value.</p>
</section>
<section id="sec-cimean-r-summ" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="sec-cimean-r-summ"><span class="header-section-number">3.9</span> Calculating a 95% confidence interval of a mean: summarised data</h2>
<p>For Worked Example 3.2 where we are given the sample mean, sample standard deviation and sample size. R does not have a built-in function to calculate a confidence interval from summarised data, but we can write our own.</p>
<p><strong>Note: writing your own functions is beyond the scope of this course. You should copy and paste the code provided to do this.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Copy this section</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ci_mean <span class="ot">&lt;-</span> <span class="cf">function</span>(n, mean, sd, <span class="at">width=</span><span class="fl">0.95</span>, <span class="at">digits=</span><span class="dv">3</span>){</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  lcl <span class="ot">&lt;-</span> mean <span class="sc">-</span> <span class="fu">qt</span>(<span class="at">p=</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>width)<span class="sc">/</span><span class="dv">2</span>), <span class="at">df=</span>n<span class="dv">-1</span>) <span class="sc">*</span> sd<span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  ucl <span class="ot">&lt;-</span> mean <span class="sc">+</span> <span class="fu">qt</span>(<span class="at">p=</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>width)<span class="sc">/</span><span class="dv">2</span>), <span class="at">df=</span>n<span class="dv">-1</span>) <span class="sc">*</span> sd<span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste0</span>(width<span class="sc">*</span><span class="dv">100</span>, <span class="st">"%"</span>, <span class="st">" CI: "</span>, <span class="fu">format</span>(<span class="fu">round</span>(lcl, <span class="at">digits=</span>digits), <span class="at">nsmall =</span> digits),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>               <span class="st">" to "</span>, <span class="fu">format</span>(<span class="fu">round</span>(ucl, <span class="at">digits=</span>digits), <span class="at">nsmall =</span> digits) ))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="do">### End of copy</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_mean</span>(<span class="at">n=</span><span class="dv">242</span>, <span class="at">mean=</span><span class="fl">128.4</span>, <span class="at">sd=</span><span class="fl">19.56</span>, <span class="at">width=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI: 125.923 to 130.877"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_mean</span>(<span class="at">n=</span><span class="dv">242</span>, <span class="at">mean=</span><span class="fl">128.4</span>, <span class="at">sd=</span><span class="fl">19.56</span>, <span class="at">width=</span><span class="fl">0.99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "99% CI: 125.135 to 131.665"</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="activities" class="level1 unnumbered">
<h1 class="unnumbered">Activities</h1>
<section id="activity-3.1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-3.1">Activity 3.1</h3>
<p>An investigator wishes to study people living with agoraphobia (fear of open spaces). The investigator places an advertisement in a newspaper asking for volunteer participants. A total of 100 replies are received of which the investigator randomly selects 30. However, only 15 volunteers turn up for their interview.</p>
<ol type="1">
<li>Which of the following statements is true?</li>
</ol>
<ol type="a">
<li>The final 15 participants are likely to be a representative sample of the population available to the investigator</li>
<li>The final 15 participants are likely to be a representative sample of the population of people with agoraphobia</li>
<li>The randomly selected 30 participants are likely to be a representative sample of people with agoraphobia who replied to the newspaper advertisement</li>
<li>None of the above</li>
</ol>
<ol start="2" type="1">
<li>The basic problem confronted by the investigator is that:</li>
</ol>
<ol type="a">
<li>The accessible population might be different from the target population</li>
<li>The sample has been chosen using an unethical method</li>
<li>The sample size was too small</li>
<li>It is difficult to obtain a sample of people with agoraphobia in a scientific way</li>
</ol>
</section>
<section id="activity-3.2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-3.2">Activity 3.2</h3>
<p>A dental epidemiologist wishes to estimate the mean weekly consumption of sweets among children of a given age in her area. After devising a method which enables her to determine the weekly consumption of sweets by a child, she conducted a pilot survey and found that the standard deviation of sweet consumption by the children per week is 85 gm (assuming this is the population standard deviation, <span class="math inline">\(\sigma\)</span>). She considers taking a random sample for the main survey of:</p>
<ul>
<li>25 children, or</li>
<li>100 children, or</li>
<li>625 children or</li>
<li>3,000 children.</li>
</ul>
<ol type="a">
<li>Estimate the standard error and maximum likely (95% confidence) error of the sample mean for each of these four sample sizes.</li>
<li>What happens to the standard error as the sample size increases? What can you say about the precision of the sample mean as the sample size increases?</li>
</ol>
</section>
<section id="activity-3.3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-3.3">Activity 3.3</h3>
<p>The dataset for this activity is the same as the one used in Activity 1.4 in Module 1. The file is <code>Activity1.4.dta</code> or <code>Activity1.4.rds</code> on Moodle.</p>
<ol type="a">
<li>Plot a histogram of diastolic BP and describe the distribution.</li>
<li>Use Stata or R to obtain an estimate of the mean, standard error of the mean and the 95% confidence interval for the mean diastolic blood pressure.</li>
<li>Interpret the 95% confidence interval for the mean diastolic blood pressure.</li>
</ol>
</section>
<section id="activity-3.4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-3.4">Activity 3.4</h3>
<p>Suppose that a random sample of 81 newborn babies delivered in a hospital located in a poor neighbourhood during the last year had a mean birth weight of 2.7 kg and a standard deviation of 0.9 kg. Calculate the 95% confidence interval for the unknown population mean. Interpret the 95% confidence interval.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bland15" class="csl-entry" role="listitem">
Bland, Martin. 2015. <em>An <span>Introduction</span> to <span>Medical Statistics</span></em>. 4th ed. <span>Oxford, New York</span>: <span>Oxford University Press</span>.
</div>
<div id="ref-kirkwood_sterne01" class="csl-entry" role="listitem">
Kirkwood, Betty, and Jonathan Sterne. 2001. <em>Essentials of <span>Medical Statistics</span></em>. 2nd ed. <span>Malden, Mass</span>: <span>Wiley-Blackwell</span>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-probability.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability and probability distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-hypothesis-testing.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>