<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>PHCM9795: Foundations of Biostatistics - 5&nbsp; Comparing the means of two groups</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-proportions.html" rel="next">
<link href="./04-hypothesis-testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: #ffdc00;
      }
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-comparing-two-means.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PHCM9795: Foundations of Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to statistics and presenting data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability and probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-precision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Precision, standard errors and confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comparing-two-means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-testing-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-correlation-and-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-non-parametrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sample size estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98.1-appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#optional-readings" id="toc-optional-readings" class="nav-link" data-scroll-target="#optional-readings">Optional readings</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#independent-samples-t-test" id="toc-independent-samples-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test"><span class="header-section-number">5.2</span> Independent samples t-test</a>
  <ul class="collapse">
  <li><a href="#assumptions-for-an-independent-samples-t-test" id="toc-assumptions-for-an-independent-samples-t-test" class="nav-link" data-scroll-target="#assumptions-for-an-independent-samples-t-test"><span class="header-section-number">5.2.1</span> Assumptions for an independent samples t-test</a></li>
  <li><a href="#worked-example" id="toc-worked-example" class="nav-link" data-scroll-target="#worked-example"><span class="header-section-number">5.2.2</span> Worked Example</a></li>
  <li><a href="#conducting-and-interpreting-an-independent-samples-t-test" id="toc-conducting-and-interpreting-an-independent-samples-t-test" class="nav-link" data-scroll-target="#conducting-and-interpreting-an-independent-samples-t-test"><span class="header-section-number">5.2.3</span> Conducting and interpreting an independent samples t-test</a></li>
  </ul></li>
  <li><a href="#paired-t-tests" id="toc-paired-t-tests" class="nav-link" data-scroll-target="#paired-t-tests"><span class="header-section-number">5.3</span> Paired t-tests</a>
  <ul class="collapse">
  <li><a href="#assumptions-for-a-paired-t-test" id="toc-assumptions-for-a-paired-t-test" class="nav-link" data-scroll-target="#assumptions-for-a-paired-t-test"><span class="header-section-number">5.3.1</span> Assumptions for a paired t-test</a></li>
  <li><a href="#computing-a-paired-t-test" id="toc-computing-a-paired-t-test" class="nav-link" data-scroll-target="#computing-a-paired-t-test"><span class="header-section-number">5.3.2</span> Computing a paired t-test</a></li>
  <li><a href="#worked-example-5.2" id="toc-worked-example-5.2" class="nav-link" data-scroll-target="#worked-example-5.2"><span class="header-section-number">5.3.3</span> Worked Example 5.2</a></li>
  </ul></li>
  <li><a href="#stata-notes" id="toc-stata-notes" class="nav-link" data-scroll-target="#stata-notes">Stata notes</a>
  <ul class="collapse">
  <li><a href="#setting-an-observation-to-missing" id="toc-setting-an-observation-to-missing" class="nav-link" data-scroll-target="#setting-an-observation-to-missing"><span class="header-section-number">5.4</span> Setting an observation to missing</a></li>
  <li><a href="#checking-data-for-the-independent-samples-t-test" id="toc-checking-data-for-the-independent-samples-t-test" class="nav-link" data-scroll-target="#checking-data-for-the-independent-samples-t-test"><span class="header-section-number">5.5</span> Checking data for the independent samples t-test</a>
  <ul class="collapse">
  <li><a href="#producing-histograms-and-boxplots-by-a-second-variable" id="toc-producing-histograms-and-boxplots-by-a-second-variable" class="nav-link" data-scroll-target="#producing-histograms-and-boxplots-by-a-second-variable"><span class="header-section-number">5.5.1</span> Producing histograms and boxplots by a second variable</a></li>
  <li><a href="#producing-split-summary-statistics" id="toc-producing-split-summary-statistics" class="nav-link" data-scroll-target="#producing-split-summary-statistics"><span class="header-section-number">5.5.2</span> Producing split summary statistics</a></li>
  </ul></li>
  <li><a href="#independent-samples-t-test-1" id="toc-independent-samples-t-test-1" class="nav-link" data-scroll-target="#independent-samples-t-test-1"><span class="header-section-number">5.6</span> Independent samples t-test</a></li>
  <li><a href="#checking-the-assumptions-for-a-paired-t-test" id="toc-checking-the-assumptions-for-a-paired-t-test" class="nav-link" data-scroll-target="#checking-the-assumptions-for-a-paired-t-test"><span class="header-section-number">5.7</span> Checking the assumptions for a Paired t-test</a></li>
  <li><a href="#paired-t-test" id="toc-paired-t-test" class="nav-link" data-scroll-target="#paired-t-test"><span class="header-section-number">5.8</span> Paired t-Test</a></li>
  </ul></li>
  <li><a href="#r-notes" id="toc-r-notes" class="nav-link" data-scroll-target="#r-notes">R notes</a>
  <ul class="collapse">
  <li><a href="#setting-an-observation-to-missing-1" id="toc-setting-an-observation-to-missing-1" class="nav-link" data-scroll-target="#setting-an-observation-to-missing-1"><span class="header-section-number">5.9</span> Setting an observation to missing</a></li>
  <li><a href="#checking-data-for-the-independent-samples-t-test-1" id="toc-checking-data-for-the-independent-samples-t-test-1" class="nav-link" data-scroll-target="#checking-data-for-the-independent-samples-t-test-1"><span class="header-section-number">5.10</span> Checking data for the independent samples t-test</a>
  <ul class="collapse">
  <li><a href="#producing-histograms-and-boxplots-by-a-second-variable-1" id="toc-producing-histograms-and-boxplots-by-a-second-variable-1" class="nav-link" data-scroll-target="#producing-histograms-and-boxplots-by-a-second-variable-1"><span class="header-section-number">5.10.1</span> Producing histograms and boxplots by a second variable</a></li>
  <li><a href="#producing-split-summary-statistics-1" id="toc-producing-split-summary-statistics-1" class="nav-link" data-scroll-target="#producing-split-summary-statistics-1"><span class="header-section-number">5.10.2</span> Producing split summary statistics</a></li>
  </ul></li>
  <li><a href="#independent-samples-t-test-2" id="toc-independent-samples-t-test-2" class="nav-link" data-scroll-target="#independent-samples-t-test-2"><span class="header-section-number">5.11</span> Independent samples t-test</a></li>
  <li><a href="#checking-the-assumptions-for-a-paired-t-test-1" id="toc-checking-the-assumptions-for-a-paired-t-test-1" class="nav-link" data-scroll-target="#checking-the-assumptions-for-a-paired-t-test-1"><span class="header-section-number">5.12</span> Checking the assumptions for a Paired t-test</a></li>
  <li><a href="#paired-t-test-1" id="toc-paired-t-test-1" class="nav-link" data-scroll-target="#paired-t-test-1"><span class="header-section-number">5.13</span> Paired t-Test</a></li>
  </ul></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a>
  <ul class="collapse">
  <li><a href="#activity-5.1" id="toc-activity-5.1" class="nav-link" data-scroll-target="#activity-5.1">Activity 5.1</a></li>
  <li><a href="#activity-5.2" id="toc-activity-5.2" class="nav-link" data-scroll-target="#activity-5.2">Activity 5.2</a></li>
  <li><a href="#activity-5.3" id="toc-activity-5.3" class="nav-link" data-scroll-target="#activity-5.3">Activity 5.3</a></li>
  <li><a href="#activity-5.4" id="toc-activity-5.4" class="nav-link" data-scroll-target="#activity-5.4">Activity 5.4</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>By the end of this module you will be able to:</p>
<ul>
<li>Decide whether to use an independent samples t-test or a paired t-test to compare two the means of two groups;</li>
<li>Conduct and interpret the results from an independent samples t-test;</li>
<li>Describe the assumptions of an independent samples t-test;</li>
<li>Conduct and interpret the results from a paired t-test;</li>
<li>Describe the assumptions of a paired t-test;</li>
<li>Conduct an independent samples t-test and a paired t-test in Stata;</li>
<li>Report results and provide a concise summary of the findings of statistical analyses.</li>
</ul>
</section>
<section id="optional-readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="optional-readings">Optional readings</h2>
<p><span class="citation" data-cites="kirkwood_sterne01">Kirkwood and Sterne (<a href="references.html#ref-kirkwood_sterne01" role="doc-biblioref">2001</a>)</span>; Sections 7.1 to 7.5. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728">[UNSW Library Link]</a></p>
<p><span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>; Section 10.3. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730">[UNSW Library Link]</a></p>
<p><span class="citation" data-cites="acock10">Acock (<a href="references.html#ref-acock10" role="doc-biblioref">2010</a>)</span>; Section 7.7, 7.8.</p>
</section>
<section id="introduction" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">5.1</span> Introduction</h2>
<p>In Module 4, a one-sample t-test was used for comparing a single mean to a hypothesised value. In health research, we often want to compare the means between two groups. For example, in an observational study, we may want to compare cholesterol levels in people who are normal weight to the levels in people who are overweight. In a clinical trial, we may want to compare cholesterol levels in people who have been randomised to a dietary modification or to usual care. In this module, we show how to compare the means of two groups where the analysis variable is normally distributed.</p>
<p>From the decision tree presented in the Appendix, we can see that if we have a continuous outcome measure and two categorical groups that are not related, i.e.&nbsp;a binary exposure measurement, the test for such data is an independent samples t-test. The test is also sometimes called a 2-sample t-test.</p>
<p>However, in research, data are often ‘paired’ or ‘matched’, that is the two data points are related to one another. This occurs when measurements are taken:</p>
<ul>
<li>From each participant on two occasions, e.g.&nbsp;at baseline and follow-up in an experimental study or in a longitudinal cohort study;</li>
<li>From related people, e.g.&nbsp;a mother and daughter or a child and their sibling;</li>
<li>From related sites in the same person, e.g.&nbsp;from both limbs, eyes or kidneys;</li>
<li>From matched participants e.g.&nbsp;in a matched case-control study;</li>
<li>In cross-over clinical trials where the patient receives both drugs, often in random order.</li>
</ul>
<p>An independent samples t-test cannot be used for analysing paired or matched data because the assumption that the two groups are independent is violated. Treating paired or matched measurements as independent samples would artificially inflate the sample size and lead to inaccurate P values. When the data are related in a paired or matched way and the outcome is continuous, a paired t-test is the appropriate statistic to use if the data are normally distributed.</p>
</section>
<section id="independent-samples-t-test" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="independent-samples-t-test"><span class="header-section-number">5.2</span> Independent samples t-test</h2>
<p>An independent samples t-test is a parametric test that is used to assess whether the mean values of two groups are different from one another. Thus, the test is used to assess whether two mean values are similar enough to have come from the same population or whether the difference between them is so large that the two groups can be considered to have come from separate populations with different characteristics.</p>
<p>The null hypothesis is that the mean values of the two groups are not different, that is:</p>
<p>H<sub>0</sub>: (Mean<sub>2</sub> <span class="math inline">\(-\)</span> Mean<sub>1</sub>) = 0</p>
<p>Rejecting the null hypothesis using an independent samples t-test indicates that the difference between the means of the two groups is large in relation to the variability in the samples and is unlikely to be due to chance or to sampling variation.</p>
<section id="assumptions-for-an-independent-samples-t-test" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="assumptions-for-an-independent-samples-t-test"><span class="header-section-number">5.2.1</span> Assumptions for an independent samples t-test</h3>
<p>The assumptions that must be met before an independent samples t-test can be used are:</p>
<ul>
<li>The two groups are independent</li>
<li>The measurements are independent</li>
<li>The outcome variable must be continuous and must be normally distributed in each group</li>
<li>The variance in the two groups is similar (homogenous)</li>
</ul>
<p>The first two assumptions are determined by the study design. The two samples must be independent, i.e.&nbsp;if a person is in one group then they cannot be included in the other group, and the measurements within a sample must be independent, i.e.&nbsp;each person must be included in their group once only.</p>
<p>The third assumption of normality is important although t-tests are robust to some degree of non-normality as long as there are no influential outliers and, more importantly, if the sample size is large. We examined how to assess normality in Module 2. If the data are not normally distributed, it may be possible to transform them using a mathematical function such as a logarithmic transformation. If not, then we may need to use non-parametric tests. This is examined in Module 9.</p>
<p>The final assumption is homogeneity of variance between the groups. This can be verified by checking that the standard deviation (square root of the variance) of each group is similar. If the variances are different, then Welch’s t-test, an alternative version of the t-test can be used.</p>
</section>
<section id="worked-example" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="worked-example"><span class="header-section-number">5.2.2</span> Worked Example</h3>
<p>In an observational study of a random sample of 100 full term babies from the community, birth weight and gender were measured. There were 44 male babies and 56 female babies in the sample. The research question asked whether there was a difference in birth weights between boys and girls. The two groups are independent of each other and therefore an independent samples t-test can be used to test the null hypothesis that there is no difference in weight between the genders.</p>
<p>Some preliminary descriptive statistics of the distribution of the variable of interest in each group should always be obtained before a t-test is undertaken to ensure that the assumptions are met. Box plots and histograms are ideal for this. Histrograms and box plots of the data obtained in Stata using <strong>Graphics &gt; Box plot</strong> is shown in <a href="#fig-mod05-bwt-gender">Figure&nbsp;<span>5.1</span></a>. The datasets <code>mod05_birthweight.dta</code> and <code>mod05_birthweight.rds</code> are available on Moodle.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod05-bwt-gender" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/mod05/mod05-bwt-gender.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.1: Histograms and box plots of birth weight by gender</figcaption>
</figure>
</div>
</div>
</div>
<p>The plots show that the data are approximately normally distributed: the histograms are relatively bell shaped and symmetric, and the boxes are fairly symmetrical, there are no outliers, and the spread is similar in both groups as the similar length of the whiskers suggesting that the variance is homogenous.</p>
<p>We can also describe the data using summary statistics:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-5-1" class="anchored">
<table id="tab:tbl-5-1" class="huxtable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;5.1: Summary of birthweight by gender</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: bold;"><p><strong>Characteristic</strong></p></td>
<td data-quarto-table-cell-role="th" style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;"><p><strong>Female</strong></p></td>
<td data-quarto-table-cell-role="th" style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: bold;"><p><strong>Male</strong></p></td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Birthweight</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">N</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">56</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">44</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Mean (SD)</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3.59 (0.36)</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">3.42 (0.35)</td>
</tr>
<tr class="odd">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Median (IQR)</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3.53 (3.33, 3.87)</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">3.43 (3.16, 3.63)</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Range</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">2.95, 4.25</td>
<td style="text-align: center; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">2.75, 4.10</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>The table shows that girls have a mean weight of 3.59 kg (SD 0.36) and boys have a mean weight of 3.42 kg (SD 0.35) with females being heavier than males. The variabilities of birth weight, as indicated by the standard deviations, are similar.</p>
</section>
<section id="conducting-and-interpreting-an-independent-samples-t-test" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="conducting-and-interpreting-an-independent-samples-t-test"><span class="header-section-number">5.2.3</span> Conducting and interpreting an independent samples t-test</h3>
<p>An independent samples t-test provides us with a t statistic from which we can compute a P value. The computation of the t statistic is as follows:</p>
<p><span class="math display">\[t = \frac{{\overline{x}}_{1} - {\overline{x}}_{2}}{SE({\overline{x}}_{1} - {\overline{x}}_{2})}\]</span></p>
<p>with <em>n<sub>1</sub> + n<sub>2</sub></em> – 2 degrees of freedom.</p>
<p>Looking at the formula for the t-statistic, we can see that the <span class="math inline">\(t\)</span> is an estimate of how different the mean values are compared to the variability of the difference in means. So <span class="math inline">\(t\)</span> will become larger as the difference in means increases with respect to the variability.</p>
<p>Statistical software will calculate both the t and P values. If the t-value is large, the P value will be small, providing evidence against the null hypothesis of no difference between the groups.</p>
<p><a href="#tbl-ind-t">Table&nbsp;<span>5.2</span></a> summarises the results of an independent samples t-test using <code>mod05_birthweight.dta</code> or <code>mod05_birthweight.rds</code>. The process of conducting the t-test is summarised for Stata and R in the following sections.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ind-t" class="anchored">
<table id="tab:tbl-ind-t" class="huxtable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;5.2: Birthweight (kg) by sex</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: bold;">Sex</td>
<td data-quarto-table-cell-role="th" style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">n</td>
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Mean (SE)</td>
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: bold;">95% Confidence Interval</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Female</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">56</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3.59 (0.049)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">3.49 to 3.68</td>
</tr>
<tr class="odd">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Male</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">44</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3.42 (0.053)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">3.31 to 3.53</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Difference</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.17 (0.072)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">0.02 to 0.31</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Here we see that girls are heavier than boys, and the mean difference in weights between the genders is 0.17 kg (95% CI 0.02, 0.31). We are 95% confident that the true mean difference of weight between girls and boys lies between 0.02 and 0.31 kg. Note that this interval does not contain the null value of 0.</p>
<p>Here we are testing the null hypothesis of no difference in mean birthweights between females and males: a two-sided test. The t-value is calculated as 2.30 with 98 degrees of freedom, and yields a two-sided P value of 0.024, providing evidence of a difference in mean birthweight between sex.</p>
</section>
</section>
<section id="paired-t-tests" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="paired-t-tests"><span class="header-section-number">5.3</span> Paired t-tests</h2>
<p>If the outcome of interest is the difference in the continuously outcome measurement between each pair of observations, a paired t-test is used. In effect, a paired t-test is used to assess whether the mean of the differences between the two related measurements is significantly different from zero. In this sense, a paired t-test is very closely aligned with a one sample t-test.</p>
<p>When using a paired t-test, the variation <em>between the pairs</em> of measurements is the most important statistic. The variation between the participants is of little interest.</p>
<p>For related measurements, the data for each pair of values must be entered on the same row of the spreadsheet. Thus, the number of rows in the data sheet is the number of pairs of observations. Thus, the effective sample size is the total number of pairs and not the total number of measurements.</p>
<section id="assumptions-for-a-paired-t-test" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="assumptions-for-a-paired-t-test"><span class="header-section-number">5.3.1</span> Assumptions for a paired t-test</h3>
<p>The assumptions for a paired t-test are:</p>
<ul>
<li>the outcome variable is continuous</li>
<li>the differences between the pair of the measurements are normally distributed</li>
</ul>
<p>For a paired samples t-test, it is important to test whether the <em>differences</em> between the two measurements are normally distributed. If the assumptions for a paired t-test cannot be met, a non-parametric equivalent is a more appropriate test to use (Module 9).</p>
</section>
<section id="computing-a-paired-t-test" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="computing-a-paired-t-test"><span class="header-section-number">5.3.2</span> Computing a paired t-test</h3>
<p>The null hypothesis for using a paired t-test is as follows:</p>
<p>H<sub>0</sub>: Mean (Measurement1 – Measurement2) = 0</p>
<p>To compute a t-value, the size of the mean difference between the two measurements is compared to the standard error of the paired differences, i.e.</p>
<p><span class="math display">\[t = \frac{\overline{d}}{SE(\overline{d})}\]</span></p>
<p>with <em>n</em>–1 degrees of freedom, where <em>n</em> is the number of pairs.</p>
<p>Because the standard error becomes smaller as the sample size becomes larger, the t-value increases as the sample size increases for the same mean difference.</p>
</section>
<section id="worked-example-5.2" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="worked-example-5.2"><span class="header-section-number">5.3.3</span> Worked Example 5.2</h3>
<p>A total of 107 people were recruited into a study to assess whether ankle blood pressure measured in two different sites would be the same. For each person, systolic blood pressure (SBP) was measured in two sites: dorsalis pedis and tibialis posterior.</p>
<p>The dataset mod05_ankle_bp.xls is available on Moodle. First, we need to compute the pairwise difference between SBP measured in the two sites in Stata using the <code>generate</code> command. This is shown in the Stata manual at the end of this module (Checking the assumptions for a Paired t-test). The distribution of the difference between SBP measured in dorsalis pedis and tibialis posterior is shown in <a href="#fig-mod05-sbpdiff">Figure&nbsp;<span>5.2</span></a>. The differences approximate a normal distribution and therefore a paired t-test can be used.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod05-sbpdiff" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="img/mod05/mod05-sbpdiff.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.2: Distribution of differences in ankle SBP between two sites of 107 participants</figcaption>
</figure>
</div>
</div>
</div>
<p>The paired t-test can be performed using statistical software, with a summary of the results presented in <a href="#tbl-paired-t">Table&nbsp;<span>5.3</span></a>. We can see that the mean SBP is very similar in the two sites.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-paired-t" class="anchored">
<table id="tab:tbl-paired-t" class="huxtable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;5.3: Systolic blood pressure (mmHg) measured at two sites on the ankle</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: bold;">Site</td>
<td data-quarto-table-cell-role="th" style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">n</td>
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Mean (SE)</td>
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: bold;">95% Confidence Interval</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Dorsalis pedis</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">107</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">116.7 (3.46)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">(109.9 to 123.6)</td>
</tr>
<tr class="odd">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Tibialis posterior</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">107</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">118.0 (3.43)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">(111.2 to 124.8)</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Difference</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">107</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-1.3 (1.31)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">(-3.9 to 1.3)</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>The t-value is calculated as −0.96 with 106 degrees of freedom, providing a two-sided P-value of 0.34. Thus these data provide no evidence of a difference in systolic blood pressure between the two sites.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="stata-notes" class="level1 unnumbered">
<h1 class="unnumbered">Stata notes</h1>
<section id="setting-an-observation-to-missing" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="setting-an-observation-to-missing"><span class="header-section-number">5.4</span> Setting an observation to missing</h2>
<p>Setting an incorrect observation to missing is straightforward in Stata by using the Data Editor (make sure you are in Edit mode). Click the cell containing the data to be set to missing, press the <strong>Delete</strong> key, and the press <strong>Enter</strong>.</p>
</section>
<section id="checking-data-for-the-independent-samples-t-test" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="checking-data-for-the-independent-samples-t-test"><span class="header-section-number">5.5</span> Checking data for the independent samples t-test</h2>
<section id="producing-histograms-and-boxplots-by-a-second-variable" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="producing-histograms-and-boxplots-by-a-second-variable"><span class="header-section-number">5.5.1</span> Producing histograms and boxplots by a second variable</h3>
<p>To obtain the histograms in <a href="#fig-mod05-bwt-gender">Figure&nbsp;<span>5.1</span></a> using the <code>mod05_birthweight.dta</code> data, go to <strong>Graphics &gt; Histogram</strong>. Select <code>birthweight</code> as the <strong>Variable</strong> in the <strong>Main</strong> tab. Next go to the <strong>By</strong> tab, tick <strong>Draw subgraphs for unique values of variable</strong> and select <code>gender</code> as the <strong>variable</strong> as shown below:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/hist-by-1.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>Note that we have also improved the basic histogram definition on the <strong>Main</strong> tab, by defining the <strong>Lower limit of first bin</strong> to be 2.5, and the <strong>Bin width</strong> to be 0.25kg:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/hist-by-2.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>A similar process is used to obtain the boxplots shown in <a href="#fig-mod05-bwt-gender">Figure&nbsp;<span>5.1</span></a>: go to <strong>Graphics &gt; Box plot</strong>. In the <strong>graph box – Box plots</strong> dialog box, select <code>birthweight</code> as the <strong>Variable</strong> in the <strong>Main</strong> tab. Next go to the <strong>Categories</strong> tab, tick <strong>Group 1</strong> and select <code>gender</code> as the <strong>Grouping variable</strong> as shown below.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/box-by-1.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>Click <strong>OK</strong> or <strong>Submit</strong> to produce the box plot.</p>
<p>[Command: <code>graph box birthweight, over(gender)</code>]</p>
</section>
<section id="producing-split-summary-statistics" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="producing-split-summary-statistics"><span class="header-section-number">5.5.2</span> Producing split summary statistics</h3>
<p>To produce summary statistics for a continuous variable, split by a second binary categorical variable, as in Worked Example 5.1 using <code>mod05_birthweight.dta</code>, go to <strong>Statistics &gt; Summaries, tables, and tests &gt; Summary and descriptive statistics &gt; Summary statistics</strong> . In the <strong>summarize</strong> dialog box, select <code>birthweight</code> as the <strong>Variable</strong> in the <strong>Main</strong> tab of the dialog box. Next go to the <strong>by/if/in</strong> tab, tick <strong>Repeat command by groups</strong> and select <code>gender</code> as the <strong>Variable that define groups</strong> as shown below.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/summ-by-1.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>Click <strong>OK</strong> or <strong>Submit</strong> to obtain the output as shown below.</p>
<p>[Command: <code>by gender, sort : summary birthweight</code>]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>. by gender, sort <span class="sc">:</span> summ birthweight</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="sc">--------------------------------------------------------------------------------</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="ot">-&gt;</span> gender <span class="ot">=</span> Female</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    Variable <span class="sc">|</span>        Obs        Mean    Std. Dev.       Min        Max</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="sc">-------------+---------------------------------------------------------</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a> birthweight <span class="sc">|</span>         <span class="dv">56</span>    <span class="fl">3.587411</span>    .<span class="dv">3629788</span>       <span class="fl">2.95</span>       <span class="fl">4.25</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="sc">--------------------------------------------------------------------------------</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="ot">-&gt;</span> gender <span class="ot">=</span> Male</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    Variable <span class="sc">|</span>        Obs        Mean    Std. Dev.       Min        Max</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="sc">-------------+---------------------------------------------------------</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a> birthweight <span class="sc">|</span>         <span class="dv">44</span>    <span class="fl">3.421364</span>    .<span class="dv">3536165</span>       <span class="fl">2.75</span>        <span class="fl">4.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output above is easy for copying into a report. You could also submit the summarize command with the <strong>detail</strong> option to compare the mean with the median (50th percentile) and check the minimum and maximum values for implausible values.</p>
<p>[Command: by gender, sort : sum birthweight , detail]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>. by gender, sort <span class="sc">:</span> summ birthweight, detail</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="sc">--------------------------------------------------------------------------------</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="ot">-&gt;</span> gender <span class="ot">=</span> Female</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>                         Birthweight</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="sc">-------------------------------------------------------------</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>      Percentiles      Smallest</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span>%         <span class="fl">2.95</span>           <span class="fl">2.95</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a> <span class="dv">5</span>%         <span class="fl">3.03</span>           <span class="fl">2.97</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span>%         <span class="fl">3.14</span>           <span class="fl">3.03</span>       Obs                  <span class="dv">56</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="dv">25</span>%        <span class="fl">3.325</span>           <span class="fl">3.07</span>       Sum of Wgt.          <span class="dv">56</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="dv">50</span>%         <span class="fl">3.53</span>                      Mean           <span class="fl">3.587411</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>                        Largest       Std. Dev.      .<span class="dv">3629788</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="dv">75</span>%         <span class="fl">3.88</span>            <span class="fl">4.2</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="dv">90</span>%         <span class="fl">4.15</span>            <span class="fl">4.2</span>       Variance       .<span class="dv">1317536</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="dv">95</span>%          <span class="fl">4.2</span>            <span class="fl">4.2</span>       Skewness       .<span class="dv">2453238</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="dv">99</span>%         <span class="fl">4.25</span>           <span class="fl">4.25</span>       Kurtosis       <span class="fl">1.962126</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="sc">--------------------------------------------------------------------------------</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="ot">-&gt;</span> gender <span class="ot">=</span> Male</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>                         Birthweight</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="sc">-------------------------------------------------------------</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>      Percentiles      Smallest</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span>%         <span class="fl">2.75</span>           <span class="fl">2.75</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a> <span class="dv">5</span>%         <span class="fl">2.82</span>           <span class="fl">2.79</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span>%         <span class="fl">2.85</span>           <span class="fl">2.82</span>       Obs                  <span class="dv">44</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="dv">25</span>%         <span class="fl">3.15</span>           <span class="fl">2.85</span>       Sum of Wgt.          <span class="dv">44</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="dv">50</span>%         <span class="fl">3.43</span>                      Mean           <span class="fl">3.421364</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>                        Largest       Std. Dev.      .<span class="dv">3536165</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="dv">75</span>%        <span class="fl">3.635</span>           <span class="fl">3.94</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="dv">90</span>%          <span class="fl">3.9</span>           <span class="fl">3.97</span>       Variance       .<span class="dv">1250446</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="dv">95</span>%         <span class="fl">3.97</span>           <span class="fl">4.06</span>       Skewness      <span class="sc">-</span>.<span class="dv">0895932</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="dv">99</span>%          <span class="fl">4.1</span>            <span class="fl">4.1</span>       Kurtosis       <span class="fl">2.325761</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="independent-samples-t-test-1" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="independent-samples-t-test-1"><span class="header-section-number">5.6</span> Independent samples t-test</h2>
<p>To carry out an independent sample t-test, go to <strong>Statistics &gt; Summaries, tables, and tests &gt; Classical tests of hypotheses &gt; t test (mean-comparison test)</strong>. In the <strong>ttest</strong> dialog box, choose the <strong>Two-sample using groups</strong> button, then select <code>birthweight</code> as the <strong>Variable</strong> name and <code>gender</code> as the <strong>Group</strong> variable name as shown below. Because the variances of <code>birthweight</code> are similar for males and females, we can leave the <strong>Unequal variances</strong> box unchecked.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/ttest-1.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>Click <strong>OK</strong> or <strong>Submit</strong> to obtain the following output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Two<span class="sc">-</span>sample t test with equal variances</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="sc">------------------------------------------------------------------------------</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>   Group <span class="sc">|</span>     Obs        Mean    Std. Err.   Std. Dev.   [<span class="dv">95</span>% Conf. Interval]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="sc">---------+--------------------------------------------------------------------</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  Female <span class="sc">|</span>      <span class="dv">56</span>    <span class="fl">3.587411</span>    .<span class="dv">0485051</span>    .<span class="dv">3629788</span>    <span class="fl">3.490204</span>    <span class="fl">3.684617</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    Male <span class="sc">|</span>      <span class="dv">44</span>    <span class="fl">3.421364</span>    .<span class="dv">0533097</span>    .<span class="dv">3536165</span>    <span class="fl">3.313854</span>    <span class="fl">3.528873</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="sc">---------+--------------------------------------------------------------------</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>combined <span class="sc">|</span>     <span class="dv">100</span>     <span class="fl">3.51435</span>    .<span class="dv">0366567</span>    .<span class="dv">3665666</span>    <span class="fl">3.441615</span>    <span class="fl">3.587085</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="sc">---------+--------------------------------------------------------------------</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    diff <span class="sc">|</span>            .<span class="dv">1660471</span>    .<span class="dv">0723027</span>                .<span class="dv">0225648</span>    .<span class="dv">3095293</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="sc">------------------------------------------------------------------------------</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    diff <span class="ot">=</span> <span class="fu">mean</span>(Female) <span class="sc">-</span> <span class="fu">mean</span>(Male)                              t <span class="ot">=</span>   <span class="fl">2.2966</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>Ho<span class="sc">:</span> diff <span class="ot">=</span> <span class="dv">0</span>                                     degrees of freedom <span class="ot">=</span>       <span class="dv">98</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    Ha<span class="sc">:</span> diff <span class="sc">&lt;</span> <span class="dv">0</span>                 Ha<span class="sc">:</span> diff <span class="sc">!=</span> <span class="dv">0</span>                 Ha<span class="sc">:</span> diff <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a> <span class="fu">Pr</span>(T <span class="sc">&lt;</span> t) <span class="ot">=</span> <span class="fl">0.9881</span>         <span class="fu">Pr</span>(<span class="sc">|</span>T<span class="sc">|</span> <span class="er">&gt;</span> <span class="er">|</span>t<span class="sc">|</span>) <span class="ot">=</span> <span class="fl">0.0238</span>          <span class="fu">Pr</span>(T <span class="sc">&gt;</span> t) <span class="ot">=</span> <span class="fl">0.0119</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>[Command: <code>ttest birthweight, by(gender)</code>]</p>
</section>
<section id="checking-the-assumptions-for-a-paired-t-test" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="checking-the-assumptions-for-a-paired-t-test"><span class="header-section-number">5.7</span> Checking the assumptions for a Paired t-test</h2>
<p>Before performing a paired t-test, you must check that the assumptions for the test have been met. Using the dataset <code>mod05_ankle_bp.xls</code> to show that the difference between the pair of measurements between the sites is normally distributed, we first need to compute a new variable of the differences.</p>
<p>Go to <strong>Data &gt; Create new variable</strong>.</p>
<p>In the <strong>generate – Create a new variable</strong> dialog box, assign a name (e.g.&nbsp;<code>difference</code>) to your new variable in the <strong>Variable name</strong> box. We want to compute difference as sbp_dp − sbp_tp, so we enter this in the <strong>Specify a value or an expression</strong> box as shown below.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/ttest-2.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>Click <strong>Submit</strong> or <strong>OK</strong>.</p>
<p>[Command: <code>generate difference = sbp_dp-sbp_tp</code>]</p>
<p>Check that the new variable appears in your Data Editor window.</p>
<p>Create a histogram with a normal curve under <strong>Graphics &gt; Histogram</strong>, as shown previously in Module 2. You might want to vary the minimum bar value and the bar width: for example, <a href="#fig-mod05-sbpdiff">Figure&nbsp;<span>5.2</span></a> was defined to have a lower limit of -40 and a bin width of 10. We have also requested a Normal curve be plotted in the <strong>Density plots</strong> tab.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/ttest-3.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>[Command: <code>histogram difference, width(10) start(-40) frequency normal</code>]</p>
</section>
<section id="paired-t-test" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="paired-t-test"><span class="header-section-number">5.8</span> Paired t-Test</h2>
<p>To perform a paired t-test we will use the dataset <code>mod05_ankle_bp.xls</code>. For a paired t-test, data must be organised into two variables (i.e.&nbsp;two columns). Go to <strong>Statistics &gt; Summaries, tables, and tests &gt; Classical tests of hypotheses &gt; t test (mean-comparison test)</strong> as you had for the Independent samples t-test. In the <strong>ttest</strong> dialog box, choose the <strong>Paired</strong> button then Select <code>sbp_dp</code> from the dropdown list under <strong>First variable</strong> and select <code>sbp_tp</code> from the dropdown list under <strong>Second variable</strong>. The dialog box will look like:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mod05/stata/ttest-4.png" class="img-fluid" style="width:66.0%"></p>
</div>
</div>
<p>Click <strong>Submit</strong> or <strong>OK</strong>. The output will look as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Paired t test</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="sc">------------------------------------------------------------------------------</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>Variable <span class="sc">|</span>     Obs        Mean    Std. Err.   Std. Dev.   [<span class="dv">95</span>% Conf. Interval]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="sc">---------+--------------------------------------------------------------------</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  sbp_dp <span class="sc">|</span>     <span class="dv">107</span>     <span class="fl">116.729</span>    <span class="fl">3.460296</span>    <span class="fl">35.79358</span>    <span class="fl">109.8686</span>    <span class="fl">123.5893</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  sbp_tp <span class="sc">|</span>     <span class="dv">107</span>    <span class="fl">117.9907</span>    <span class="fl">3.431356</span>    <span class="fl">35.49422</span>    <span class="fl">111.1877</span>    <span class="fl">124.7937</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="sc">---------+--------------------------------------------------------------------</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    diff <span class="sc">|</span>     <span class="dv">107</span>   <span class="sc">-</span><span class="fl">1.261682</span>    <span class="fl">1.311368</span>    <span class="fl">13.56489</span>   <span class="sc">-</span><span class="fl">3.861596</span>    <span class="fl">1.338232</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="sc">------------------------------------------------------------------------------</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>     <span class="fu">mean</span>(diff) <span class="ot">=</span> <span class="fu">mean</span>(sbp_dp <span class="sc">-</span> sbp_tp)                           t <span class="ot">=</span>  <span class="sc">-</span><span class="fl">0.9621</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a> Ho<span class="sc">:</span> <span class="fu">mean</span>(diff) <span class="ot">=</span> <span class="dv">0</span>                              degrees of freedom <span class="ot">=</span>      <span class="dv">106</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a> Ha<span class="sc">:</span> <span class="fu">mean</span>(diff) <span class="sc">&lt;</span> <span class="dv">0</span>           Ha<span class="sc">:</span> <span class="fu">mean</span>(diff) <span class="sc">!=</span> <span class="dv">0</span>           Ha<span class="sc">:</span> <span class="fu">mean</span>(diff) <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a> <span class="fu">Pr</span>(T <span class="sc">&lt;</span> t) <span class="ot">=</span> <span class="fl">0.1691</span>         <span class="fu">Pr</span>(<span class="sc">|</span>T<span class="sc">|</span> <span class="er">&gt;</span> <span class="er">|</span>t<span class="sc">|</span>) <span class="ot">=</span> <span class="fl">0.3382</span>          <span class="fu">Pr</span>(T <span class="sc">&gt;</span> t) <span class="ot">=</span> <span class="fl">0.8309</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>[Command: <code>ttest sbp_dp == sbp_tp</code>]</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="r-notes" class="level1 unnumbered">
<h1 class="unnumbered">R notes</h1>
<section id="setting-an-observation-to-missing-1" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="setting-an-observation-to-missing-1"><span class="header-section-number">5.9</span> Setting an observation to missing</h2>
<p>Setting an incorrect observation to missing is straightforward in Stata by using the Data Editor. While RStudio allows browsing a data set as a spreadsheet, it will not let a user replace an observation with a missing value: this should be done using code.</p>
<p>A missing value in R is denoted <code>NA</code>, and this is consistent for any variable type: continuous, string (i.e.&nbsp;character) and even a factor.</p>
<p>Recall the <code>weights</code> data used in Module 2. In viewing a boxplot of <code>weight</code>, we saw an obvious outlier of 700.2kg for ID 58:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/examples/mod02_weight_1000.csv"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(sample<span class="sc">$</span>weight, <span class="at">xlab=</span><span class="st">"Weight (kg)"</span>, <span class="at">main=</span><span class="st">"Boxplot of 1000 weights"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="05-comparing-two-means_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(sample, weight<span class="sc">&gt;</span><span class="dv">200</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table id="tab:unnamed-chunk-8" class="huxtable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">id</td>
<td data-quarto-table-cell-role="th" style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">weight</td>
</tr>
<tr class="even">
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">58</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">700</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>We previously set this value to 70.2kg using an <code>ifelse()</code> command. Here, let’s create a new, cleaned weight variable, and set the incorrect value to missing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sample<span class="sc">$</span>weight_clean <span class="ot">=</span> <span class="fu">ifelse</span>(sample<span class="sc">$</span>weight<span class="sc">==</span><span class="fl">700.2</span>, <span class="cn">NA</span>, sample<span class="sc">$</span>weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our code will create a new column (called weight_clean) in the <code>sample</code> dataframe. We will test whether weight is equal to 700.2; if this is true, we will assign weight_clean to be NA (i.e.&nbsp;missing), otherwise weight_clean will equal the value of weight.</p>
<p>Let’s view the data from ID 58, and summarise the cleaned weight variable using <code>descriptives()</code> and a boxplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(sample, sample<span class="sc">$</span>id<span class="sc">==</span><span class="dv">58</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table id="tab:unnamed-chunk-10" class="huxtable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">id</td>
<td data-quarto-table-cell-role="th" style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">weight</td>
<td data-quarto-table-cell-role="th" style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">weight_clean</td>
</tr>
<tr class="even">
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">58</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">700</td>
<td style="text-align: right; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>sample, <span class="at">vars=</span>weight_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                           
 ────────────────────────────────────── 
                         weight_clean   
 ────────────────────────────────────── 
   N                              999   
   Missing                          1   
   Mean                      69.76406   
   Median                    69.80000   
   Standard deviation        5.055188   
   Minimum                   53.80000   
   Maximum                   85.80000   
 ────────────────────────────────────── </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(sample<span class="sc">$</span>weight_clean, <span class="at">xlab=</span><span class="st">"Weight (kg)"</span>, <span class="at">main=</span><span class="st">"Boxplot of 999 weights"</span>,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub=</span><span class="st">"(Excluding 1 observation of 700.2kg)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="05-comparing-two-means_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="checking-data-for-the-independent-samples-t-test-1" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="checking-data-for-the-independent-samples-t-test-1"><span class="header-section-number">5.10</span> Checking data for the independent samples t-test</h2>
<section id="producing-histograms-and-boxplots-by-a-second-variable-1" class="level3" data-number="5.10.1">
<h3 data-number="5.10.1" class="anchored" data-anchor-id="producing-histograms-and-boxplots-by-a-second-variable-1"><span class="header-section-number">5.10.1</span> Producing histograms and boxplots by a second variable</h3>
<p>We have seen how to create histograms and boxplots separated by a second variable in Module 2 (REF). We will demonstrate using the birthweight data in <code>mod05_birthweight.rds</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>bwt <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/examples/mod05_birthweight.rds"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bwt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    gender    birthweight   
 Female:56   Min.   :2.750  
 Male  :44   1st Qu.:3.257  
             Median :3.450  
             Mean   :3.514  
             3rd Qu.:3.772  
             Max.   :4.250  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bwt<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Female   Male 
    56     44 </code></pre>
</div>
</div>
<p>We can create subsets of the birthweight data, subsetted for males and females separately. Note here that <code>gender</code> is a factor, so we need to select based on the factor labels, not the underlying numeric code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>bwt_m <span class="ot">&lt;-</span> <span class="fu">subset</span>(bwt, bwt<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"Male"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>bwt_f <span class="ot">&lt;-</span> <span class="fu">subset</span>(bwt, bwt<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"Female"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now create histograms and boxplots for males and females separately, in the usual way, using the <code>par</code> function to set the graphics parameters to display graphs in a 2-by-2 grid:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bwt_m<span class="sc">$</span>birthweight, <span class="at">xlim=</span><span class="fu">c</span>(<span class="fl">2.5</span>, <span class="fl">4.5</span>), <span class="at">xlab=</span><span class="st">"Birthweight (kg)"</span>, <span class="at">main=</span><span class="st">"Males"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bwt_f<span class="sc">$</span>birthweight, <span class="at">xlim=</span><span class="fu">c</span>(<span class="fl">2.5</span>, <span class="fl">4.5</span>), <span class="at">xlab=</span><span class="st">"Birthweight (kg)"</span>, <span class="at">main=</span><span class="st">"Females"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(bwt_m<span class="sc">$</span>birthweight, <span class="at">ylim=</span><span class="fu">c</span>(<span class="fl">2.5</span>, <span class="fl">4.5</span>), <span class="at">ylab=</span><span class="st">"Birthweight (kg)"</span>, <span class="at">main=</span><span class="st">"Males"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(bwt_f<span class="sc">$</span>birthweight, <span class="at">ylim=</span><span class="fu">c</span>(<span class="fl">2.5</span>, <span class="fl">4.5</span>), <span class="at">ylab=</span><span class="st">"Birthweight (kg)"</span>, <span class="at">main=</span><span class="st">"Females"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="05-comparing-two-means_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we are done plotting multiple graphs, we can reset the plot window by submitting <code>par(mfrow=c(1,1))</code>.</p>
</section>
<section id="producing-split-summary-statistics-1" class="level3" data-number="5.10.2">
<h3 data-number="5.10.2" class="anchored" data-anchor-id="producing-split-summary-statistics-1"><span class="header-section-number">5.10.2</span> Producing split summary statistics</h3>
<p>The <code>descriptives</code> function within the <code>jmv</code> function allows summary statistics to be calculated within subgroups using the <code>splitBy</code> argument:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>bwt, <span class="at">vars=</span>birthweight, <span class="at">splitBy=</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                    
 ─────────────────────────────────────────────── 
                         gender    birthweight   
 ─────────────────────────────────────────────── 
   N                     Female             56   
                         Male               44   
   Missing               Female              0   
                         Male                0   
   Mean                  Female       3.587411   
                         Male         3.421364   
   Median                Female       3.530000   
                         Male         3.430000   
   Standard deviation    Female      0.3629788   
                         Male        0.3536165   
   Minimum               Female       2.950000   
                         Male         2.750000   
   Maximum               Female       4.250000   
                         Male         4.100000   
 ─────────────────────────────────────────────── </code></pre>
</div>
</div>
</section>
</section>
<section id="independent-samples-t-test-2" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="independent-samples-t-test-2"><span class="header-section-number">5.11</span> Independent samples t-test</h2>
<p>We can use the <code>ttestIS()</code> (t-test, independent samples) function from the <code>jmv</code> package to perform the independent samples t-test. We include the <code>meanDiff=TRUE</code> and <code>ci=TRUE</code> options to obtain the difference in means, with its 95% confidence interval. We can request a Welch’s test (which does not assume equal variances) by the <code>welchs=TRUE</code> option:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestIS</span>(<span class="at">data=</span>bwt, <span class="at">vars=</span>birthweight, <span class="at">group=</span>gender, <span class="at">meanDiff=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 INDEPENDENT SAMPLES T-TEST

 Independent Samples T-Test                                                                                                          
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
                                 Statistic    df          p            Mean difference    SE difference    Lower         Upper       
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
   birthweight    Student's t     2.296556    98.00000    0.0237731          0.1660471       0.07230265    0.02256481    0.3095293   
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestIS</span>(<span class="at">data=</span>bwt, <span class="at">vars=</span>birthweight, <span class="at">group=</span>gender, <span class="at">meanDiff=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>, <span class="at">welchs=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 INDEPENDENT SAMPLES T-TEST

 Independent Samples T-Test                                                                                                          
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
                                 Statistic    df          p            Mean difference    SE difference    Lower         Upper       
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
   birthweight    Student's t     2.296556    98.00000    0.0237731          0.1660471       0.07230265    0.02256481    0.3095293   
                  Welch's t       2.303840    93.54377    0.0234458          0.1660471       0.07207403    0.02293328    0.3091609   
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── </code></pre>
</div>
</div>
<p>There is no built-in function to calculate an independent t-test from summarised data, nor is there a function within <code>jmv</code>. We can use the <code>tsum.test()</code> function within the <code>BSDA</code> package, with the following syntax:</p>
<pre><code>tsum.test(mean.x=, s.x=, n.x=,
          mean.y=, s.y=, n.y=,
          mu=0, alternative="two.sided", var.equal = TRUE)</code></pre>
<p>Here we specify the mean, standard deviation and sample size for the first group (on the first line) and the second group (on the second line). We can relax the assumption of equal variances using <code>var.equal=FALSE</code>.</p>
</section>
<section id="checking-the-assumptions-for-a-paired-t-test-1" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="checking-the-assumptions-for-a-paired-t-test-1"><span class="header-section-number">5.12</span> Checking the assumptions for a Paired t-test</h2>
<p>Before performing a paired t-test, you must check that the assumptions for the test have been met. Using the dataset <code>mod05_ankle_bp.xls</code> to show that the difference between the pair of measurements between the sites is normally distributed, we first need to compute a new variable of the differences and examine its histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>sbp <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/examples/mod05_ankle_bp.xlsx"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>sbp<span class="sc">$</span>diff <span class="ot">=</span> sbp<span class="sc">$</span>sbp_dp <span class="sc">-</span> sbp<span class="sc">$</span>sbp_tp</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sbp<span class="sc">$</span>diff, <span class="at">xlab=</span><span class="st">"Blood pressure (mmHg)"</span>, <span class="at">main=</span><span class="st">"Difference in systolic blood pressure"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="05-comparing-two-means_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We might want to plot a Normal curve over this distribution, as we did in Module 2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sbp<span class="sc">$</span>diff,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Systolic blood pressure (mmHg)"</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Difference in systolic blood pressure"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">probability =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean=</span><span class="fu">mean</span>(sbp<span class="sc">$</span>diff),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd=</span><span class="fu">sd</span>(sbp<span class="sc">$</span>diff)),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">col=</span><span class="st">"darkblue"</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">add=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="05-comparing-two-means_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While there is a large difference in blood pressure (around 60 mmHg) that warrents further checking, the curve is roughly symmetric with an approximately Normal distribution.</p>
</section>
<section id="paired-t-test-1" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="paired-t-test-1"><span class="header-section-number">5.13</span> Paired t-Test</h2>
<p>To perform a paired t-test we will use the dataset <code>mod05_ankle_bp.xls</code>. We can perform a paired t-test using the <code>ttestPS()</code> function within the <code>jmv</code> package, where we defined the paired observations as: `pairs=list(list(i1 = ‘variable1’, i2 = ‘variable2’))</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestPS</span>(<span class="at">data=</span>sbp, <span class="at">pairs=</span><span class="fu">list</span>(<span class="fu">list</span>(<span class="at">i1 =</span> <span class="st">'sbp_dp'</span>, <span class="at">i2 =</span> <span class="st">'sbp_tp'</span>)), <span class="at">meanDiff=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 PAIRED SAMPLES T-TEST

 Paired Samples T-Test                                                                                                                   
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
                                      statistic     df          p            Mean difference    SE difference    Lower        Upper      
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
   sbp_dp    sbp_tp    Student's t    -0.9621117    106.0000    0.3381832          -1.261682         1.311368    -3.861596    1.338232   
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── </code></pre>
</div>
</div>
<p>The syntax of the ttestPS function is a little cumbersome. The <code>t.test</code> function can be used as an alternative:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sbp<span class="sc">$</span>sbp_dp, sbp<span class="sc">$</span>sbp_tp, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  sbp$sbp_dp and sbp$sbp_tp
t = -0.96211, df = 106, p-value = 0.3382
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -3.861596  1.338232
sample estimates:
mean difference 
      -1.261682 </code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="activities" class="level1 unnumbered">
<h1 class="unnumbered">Activities</h1>
<section id="activity-5.1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.1">Activity 5.1</h3>
<p>Indicate what type of t-test could be used to analyse the data from the following studies and provide reasons:</p>
<ol type="a">
<li>A total of 60 university students are randomly assigned to undergo either behaviour therapy or Gestalt therapy. After twenty therapeutic sessions, each student earns a score on a mental health questionnaire.</li>
<li>A researcher wishes to determine whether attendance at a day care centre increases the scores of three year old twins on a motor skills test. Random assignment is used to decide which member from each of 30 pairs of twins attends the day care centre and which member stays at home.</li>
<li>A child psychologist assigns aggression scores to each of 10 children during two 60 minute observation periods separated by an intervening exposure to a series of violent TV cartoons.</li>
<li>A marketing researcher measures 100 doctors’ reports of the number of their patients asking them about a particular drug during the month before and the month after a major advertising campaign.</li>
</ol>
</section>
<section id="activity-5.2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.2">Activity 5.2</h3>
<p>A study was conducted to compare haemoglobin levels in the blood of children with and without cystic fibrosis. It is known that haemoglobin levels are normally distributed in children. The study results are given below:</p>
<div class="cell">
<div class="cell-output-display">
<table id="tab:act-5-2" class="huxtable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary of haemoglobin (g/dL)</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: bold;">Statistic</td>
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Children without CF</td>
<td data-quarto-table-cell-role="th" style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: bold;">Children with CF</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">n</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">12</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">Mean</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">19.9</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">13.9</td>
</tr>
<tr class="even">
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 0pt; font-weight: normal;">SD (SE)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">5.9 (1.70)</td>
<td style="text-align: left; vertical-align: top; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 6pt 0pt 6pt 6pt; font-weight: normal;">6.2 (1.60)</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="a">
<li>State the appropriate null hypothesis and alternate hypothesis</li>
<li>Use Stata to conduct an appropriate statistical test to evaluate the null hypothesis. Are the assumptions for the test met for this analysis to be valid?</li>
</ol>
</section>
<section id="activity-5.3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.3">Activity 5.3</h3>
<p>A randomised controlled trial (RCT) was carried out to investigate the effect of a new tablet supplement in increasing the hematocrit (%) value in anaemic participants. In the study, hematocrit was measured as the proportion of blood that is made up of red blood cells. Hematocrit levels are often lower in anaemic people who do not have sufficient healthy red blood cells. In the RCT, 33 people in the intervention group received the new supplement and 31 people in the control group received standard care (i.e.&nbsp;the usual supplement was given). After 4 weeks, hematocrit values were measured as entered in the files <code>Activity_S5.3.dta</code> and <code>Activity_S5.3.rds</code>. In the community, hematocrit levels are normally distributed.</p>
<ol type="a">
<li>State the research question and frame it as a null hypothesis.</li>
<li>Use Stata to conduct an appropriate statistical test to answer the research question. Before using the test, check the data to see if the assumptions required for the test are met. Obtain a box plot to obtain an estimate of the centre and spread of the data for each group.</li>
<li>Run your statistical test.</li>
<li>Construct a table to show how you would report your results and write a conclusion.</li>
</ol>
</section>
<section id="activity-5.4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.4">Activity 5.4</h3>
<p>A total of 41 babies aged 6 months to 2 years with haemangioma (birth mark) were enrolled in a study to test the effect of a new topical medication in reducing the volume of their haemangioma. Parents were asked to apply the medication twice daily. The volume (in mm3) of the haemangioma was measured at enrolment and again after 12 weeks of using the medication.</p>
<ol type="a">
<li>What is the research question in this study? State the null and alternative hypotheses.</li>
<li>Use the data in the files <code>ActivityS5.4.dta</code> or <code>Activity_S5.4.rds</code> to answer the research question. Which statistical test is appropriate to answer the research question and why? Conduct the test and write your conclusion.</li>
<li>What are the limitations of this study?</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-acock10" class="csl-entry" role="listitem">
Acock, Alan C. 2010. <em>A <span>Gentle Introduction</span> to <span>Stata</span></em>. 3rd ed. <span>College Station, Tex</span>: <span>Stata Press</span>.
</div>
<div id="ref-bland15" class="csl-entry" role="listitem">
Bland, Martin. 2015. <em>An <span>Introduction</span> to <span>Medical Statistics</span></em>. 4th ed. <span>Oxford, New York</span>: <span>Oxford University Press</span>.
</div>
<div id="ref-kirkwood_sterne01" class="csl-entry" role="listitem">
Kirkwood, Betty, and Jonathan Sterne. 2001. <em>Essentials of <span>Medical Statistics</span></em>. 2nd ed. <span>Malden, Mass</span>: <span>Wiley-Blackwell</span>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-hypothesis-testing.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-proportions.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>